### PR TITLE
Sort KEYWORDS for consistent output ordering

### LINKED ISSUE #40: Consistent keyword ordering
Every time I run pegen on the same grammar, I (often) get a different order for `KEYWORDS` and `SOFT_KEYWORDS`.  This is annoying for version control, when `parse.py` is committed to a repo.

I imagine the cause is that the keywords are stored in a `set` which has nondeterministic order, and `sorted` will make this behavior deterministic.  Specifically, `tuple(...)` should be replaced with `tuple(sorted(...))` in these lines:

https://github.com/we-like-parsers/pegen/blob/31f489a16ba961be2b7142789f54e4a02561acbc/src/pegen/python_generator.py#L240-L241

Is it appropriate to make PR here, or would it be better against cpython?

### PR DESCRIPTION
**Pull request by edemaine**
Fixes #40 by adding `sorted(...)` as suggested previously.

I could use some guidance for writing tests.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
I am not sure either how to best test this feature. And actually currently no test validate the content of the KEYWORDS and SOFT_KEYWORDS attributes. So you could add a test under test_pegen.py generating a parser from a small grammar containing both hard and soft keywords and testing that the output is as expected. The other tests there should illustrate how to easily generate the parser class. Let me know if you need further guidance.

**Comment by edemaine** [comment]
Thanks for the guidance! I've added a test that seems to do the job.

**Review by lysnikolaou — APPROVED** [review]
LGTM! Thanks @edemaine for the PR!

**Comment by pablogsal** [comment]
Thanks, @edemaine! 🎉

**Pull request merged**
