### PR TITLE
Replace nullable_visit by NullableVisitor

### PR DESCRIPTION
**Pull request by phorward**
This introduces the NullableVisitor from CPython's pegen.

---
This is part of the former PR #85.
I was able to run the test-suite locally, using pipenv and python38.
Generally, should we not upgrade to latest python310 with all pegen development?

### CODE REVIEW

**Review by pablogsal — DISMISSED** [review]

**Comment by pablogsal** [comment]
@phorward please don't force push after an approval because it forces us to dismiss the review and review again everything :)

**Comment by phorward** [comment]
Hello @pablogsal, I hope you're doing well.

Can you please take another review and maybe merge on this pull request? I've started to work on a pull request setting-up on this one, to successively transfer all overrides from the CPython version of pegen to the stand-alone project. It is important for me to have the stand-alone pegen in similar code-base as the CPython version, to start with further developments on it.

I would like to share my vision of pegen in some kind, if interested, as it may become a universal PEG-like parser generator not only limited to Python. Please contact me, or provide a way to share ideas.

**Review by lysnikolaou — APPROVED** [review]
LGTM!

**Comment by lysnikolaou** [comment]
@phorward Thanks for the PR and sorry for taking so long on this. We've been very busy with other things and this fell further down in our list of to-dos.

If you want to start a discussion on ideas you have for the project, an issue would be the best way forward. Please open one, and I'd be happy to get a conversation going there.

**Comment by phorward** [comment]
> @phorward Thanks for the PR and sorry for taking so long on this. We've been very busy with other things and this fell further down in our list of to-dos.

No problem, thanks for merging. Can you please check the GitHub action job that is currently pending, so that the merge becomes complete?

> If you want to start a discussion on ideas you have for the project, an issue would be the best way forward. Please open one, and I'd be happy to get a conversation going there.

Ok thanks. I wrote some ideas down on a vision for pegen in my fork [anypeg](https://github.com/phorward/anypeg/blob/anypeg/vision.md), but I think it'll be the best to divide it into separate issues to easier maintain and focus on.

**Pull request merged**
